version: "3.8"
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: domipyme
      POSTGRES_USER: domipyme
      POSTGRES_PASSWORD: domipyme
    volumes:
      - postgres_data:/var/lib/postgresql/data
  web:
    build: .
    command: >
      sh -c "python manage.py migrate --no-input &&
             python manage.py collectstatic --no-input &&
             gunicorn config.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_ENGINE: "postgres"
      POSTGRES_DB: domipyme
      POSTGRES_USER: domipyme
      POSTGRES_PASSWORD: domipyme
      POSTGRES_HOST: db
volumes:
  postgres_data:
